server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rk_payment
    username: postgres
    password: user
  jpa:
    generate-ddl: true
  application:
    name: rk-payment-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

stripe:
  api-key: sk_test_cPFnlTE1PZoNYEJAppyCX0st00aIDM9PbS
client:
  base-url: http://localhost:4201